version: "3"
services:
  db:
    image: mongo:3.0
    volumes:
      - ./data/runtime/db:/data/db
      - ./data/dump:/dump
    command: mongod --smallfiles

  rocketchat:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://db:27017/rocketchat
      - ROOT_URL=http://localhost
    ports:
      - 3000:3000
  hubot:
    build:
      context: .
      dockerfile: Dockerfile-hubot
    #image: rocketchat/hubot-rocketchat:v1.0.3
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - RESPOND_TO_DM=true
      - ROCKETCHAT_ROOM=
      - LISTEN_ON_ALL_PUBLIC=true
      - ROCKETCHAT_USER=rocketbot
      - ROCKETCHAT_PASSWORD=rocket123
      - BOT_NAME=mbot
      - GOOGLE_API_KEY=AIzaSyCHqXtrGPeUe2RhhCLxrDhB1x6veJ4IaZw
      - HUBOT_AUTH_ADMIN=ec2-user,root
      - HUBOT_AWS_REGION=us-east-1
      - HUBOT_AWS_DEBUG=1
      - AWS_ACCOUNT_ID=291890047404
      #- HUBOT_LOG_LEVEL=debug
      #- NODE_DEBUG=module
  # you can add more scripts as you'd like here, they need to be installable by npm
      #- EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot-google,hubot-reddit,hubot-bofh,hubot-bookmark,hubot-shipit,hubot-maps,hubot-aws,hubot-auth
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080
    volumes:
    ./scripts:/home/hubot/scripts
